name: Build Specification

on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Release version, e.g. X.Y.Z:'
          required: true
          type: string
        prerelease:
          description: 'Tag as a pre-release?'
          required: false
          type: boolean
          default: true
        draft:
          description: 'Create release as a draft?'
          required: false
          type: boolean
          default: false
    pull_request:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build Docker Image
      run: docker build -t latex-make-env .

    - name: Run Container & Compile LaTeX
      run: |
        docker run --rm -v ${{ github.workspace }}:/data latex-make-env bash -c "\
        git config --global --add safe.directory /data && \
        make"

    # Step 4: Upload the built PDF files as a single artifact
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Specification Artifact
        path: ${{ github.workspace }}/*.pdf
        retention-days: 30
      
    # Create Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/*.pdf
        tag_name: v${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        draft: ${{ github.event.inputs.draft }}
        prerelease: ${{ github.event.inputs.prerelease }}
      env:
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
      if: github.event_name == 'workflow_dispatch' 